services:

  backend:
    build: ./backend   # ← Javaプロジェクト（ルート）
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
# リンク　http://localhost:5173/

  db:
    image: postgres:16
    container_name: nippo-db
    environment:
      POSTGRES_DB: nippo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mynippo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data