spring:
  application:
    name: packend

  datasource:
    url: jdbc:postgresql://localhost:5432/nippo_db
    username: postgres
    password: mynippo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  # メール設定追加
  mail:
    host: smtp.gmail.com
    port: 587
    username: yoo.yeonmi@no1s.biz // 自分のメールアドレスを設定
    password: ${MAIL_PASSWORD} // 自分のアプリパスワードを設定
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # セキュリティ連結(TLS) 活性化