spring:
  application:
    name: packend

  datasource:
    # 도커 내부에서 실행할 때는 localhost 대신 서비스 이름인 'db'를 써야 합니다!
    url: jdbc:postgresql://localhost:5432/nippo_db
    username: postgres
    password: mynippo
    driver-class-name: org.postgresql.Driver
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect # 방언 설정 추가 (권장)
      format_sql: true
  show-sql: true